/* eslint quote-props: ["error", "consistent"] */
/* eslint object-curly-spacing: ["error", "always"] */
'use strict';

// Using 0 instead of "off" so that the our tests can assert that only rules
// that prettier actually conflicts are marked as "prettier".
const PRETTIER = 0;

module.exports = {
  env: {
    node: true,
    es6: true,
    es2017: true,
    es2020: true,
  },
  extends: ['eslint:recommended', 'prettier'],
  parserOptions: {
    ecmaVersion: 2020,
  },
  rules: {
    // Possible Errors
    'for-direction': 'error',
    'getter-return': 'error',
    'no-async-promise-executor': 'error',
    'no-await-in-loop': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-console': 'error',
    'no-constant-condition': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-dupe-args': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-ex-assign': 'error',
    'no-extra-boolean-cast': 'error',
    'no-extra-parens': PRETTIER,
    'no-extra-semi': PRETTIER,
    'no-func-assign': 'error',
    'no-import-assign': 'error',
    'no-inner-declarations': ['error', 'functions'],
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-misleading-character-class': 'error',
    'no-obj-calls': 'error',
    'no-prototype-builtins': 'error',
    'no-regex-spaces': 'error',
    'no-sparse-arrays': 'error',
    'no-template-curly-in-string': 'error',
    'no-unexpected-multiline': 'error',
    'no-unreachable': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': ['error', { enforceForOrderingRelations: true }],
    'use-isnan': 'error',
    'require-atomic-updates': 'warn', // see: https://github.com/eslint/eslint/issues/11899
    'valid-typeof': 'error',

    // Best Practices
    'accessor-pairs': 'error',
    'array-callback-return': 'error',
    'block-scoped-var': 'error',
    'class-methods-use-this': 'error',
    'complexity': 'error',
    'consistent-return': 'off',
    'curly': 'error',
    'default-case': 'error',
    'default-param-last': 'error',
    'dot-location': PRETTIER,
    'dot-notation': 'error',
    'eqeqeq': 'error',
    'guard-for-in': 'warn',
    'max-classes-per-file': 'off',
    'no-alert': 'error',
    'no-caller': 'error',
    'no-case-declarations': 'error',
    'no-div-regex': 'error',
    'no-else-return': 'error',
    'no-empty-function': 'error',
    'no-empty-pattern': 'error',
    'no-eq-null': 'error',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-label': 'error',
    'no-fallthrough': 'error',
    'no-floating-decimal': PRETTIER,
    'no-global-assign': 'error',
    'no-implicit-coercion': 'error',
    'no-implicit-globals': 'error',
    'no-implied-eval': 'error',
    'no-invalid-this': 'off', // Doesn't work with Promise.bind()
    'no-iterator': 'error',
    'no-labels': 'error',
    'no-lone-blocks': 'error',
    'no-loop-func': 'error',
    'no-magic-numbers': 'off',
    'no-multi-spaces': PRETTIER,
    'no-multi-str': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-octal': 'error',
    'no-octal-escape': 'error',
    'no-param-reassign': 'off',
    'no-proto': 'error',
    'no-redeclare': ['error', { builtinGlobals: true }],
    'no-restricted-properties': 'off',
    'no-return-assign': 'error',
    'no-return-await': 'error',
    'no-script-url': 'error',
    'no-self-assign': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-throw-literal': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unused-expressions': 'error',
    'no-unused-labels': 'error',
    'no-useless-call': 'error',
    'no-useless-catch': 'error',
    'no-useless-concat': 'error',
    'no-useless-escape': 'error',
    'no-useless-return': 'error',
    'no-void': 'error',
    'no-warning-comments': 'off',
    'no-with': 'error',
    'prefer-named-capture-group': 'error',
    'prefer-promise-reject-errors': 'error',
    'prefer-regex-literals': 'error',
    'radix': ['error', 'as-needed'],
    'require-await': 'error',
    'require-unicode-regexp': 'error',
    'vars-on-top': 'off',
    'wrap-iife': PRETTIER,
    'yoda': ['error', 'never', { exceptRange: true }],
    'strict': ['error', 'safe'],

    // Variables
    'init-declarations': 'off',
    'no-delete-var': 'error',
    'no-label-var': 'error',
    'no-restricted-globals': 'error',
    'no-shadow': 'off',
    'no-shadow-restricted-names': 'error',
    'no-undef': 'error',
    'no-undef-init': 'error',
    'no-undefined': 'off',
    'no-unused-vars': ['error', { vars: 'all', args: 'after-used' }],
    'no-use-before-define': ['error', { functions: false, classes: true }],

    // nodejs & commonjs
    'callback-return': 'error',
    'global-require': 'error',
    'handle-callback-err': 'error',
    'no-buffer-constructor': 'error',
    'no-mixed-requires': 'error',
    'no-new-require': 'error',
    'no-path-concat': 'error',
    'no-process-env': 'error',
    'no-process-exit': 'error',
    'no-restricted-modules': 'off',
    'no-sync': ['error', { allowAtRootLevel: true }],

    // Style
    'array-bracket-newline': PRETTIER,
    'array-bracket-spacing': PRETTIER,
    'array-element-newline': PRETTIER,
    'block-spacing': PRETTIER,
    'brace-style': PRETTIER,
    'camelcase': ['error', { properties: 'always' }],
    'capitalized-comments': 'off',
    'comma-dangle': PRETTIER,
    'comma-spacing': PRETTIER,
    'comma-style': PRETTIER,
    'computed-property-spacing': PRETTIER,
    'consistent-this': ['error', 'self'],
    'eol-last': PRETTIER,
    'func-call-spacing': PRETTIER,
    'func-name-matching': 'error',
    'func-names': 'off',
    'func-style': 'off',
    'function-call-argument-newline': PRETTIER,
    'function-paren-newline': PRETTIER,
    'id-blacklist': 'off',
    'id-length': 'off',
    'id-match': 'off',
    'implicit-arrow-linebreak': PRETTIER,
    'indent': PRETTIER,
    'jsx-quotes': PRETTIER,
    'key-spacing': PRETTIER,
    'keyword-spacing': PRETTIER,
    'line-comment-position': 'off', // too opinionated
    'linebreak-style': PRETTIER,
    'lines-around-comment': 'off',
    'lines-between-class-members': [
      'error',
      'always',
      { exceptAfterSingleLine: true },
    ],
    'max-depth': ['error', 4],
    'max-len': [
      'error',
      {
        code: 80,
        comments: 90,
        ignoreUrls: true,
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
        ignoreRegExpLiterals: true,
        ignorePattern: '^\\s*(.+=\\s*(require|rewire)|test)\\s*\\(',
      },
    ],
    'max-lines': 'off',
    'max-lines-per-function': 'off',
    'max-nested-callbacks': ['error', 5],
    'max-params': ['error', 6],
    'max-statements': 'off',
    'max-statements-per-line': ['error', { max: 2 }],
    'multiline-comment-style': 'off',
    'multiline-ternary': PRETTIER,
    'new-cap': ['error', { newIsCap: true, capIsNew: false }],
    'new-parens': PRETTIER,
    'newline-per-chained-call': PRETTIER,
    'no-array-constructor': 'error',
    'no-bitwise': 'warn',
    'no-continue': 'off',
    'no-inline-comments': 'off',
    'no-lonely-if': 'error',
    'no-mixed-operators': 'error',
    'no-mixed-spaces-and-tabs': PRETTIER,
    'no-multi-assign': 'error',
    'no-multiple-empty-lines': PRETTIER,
    'no-negated-condition': 'off',
    'no-nested-ternary': 'error',
    'no-new-object': 'error',
    'no-plusplus': 'off',
    'no-restricted-syntax': 'off',
    'no-ternary': 'off',
    'no-tabs': 'error',
    'no-trailing-spaces': PRETTIER,
    'no-underscore-dangle': 'off',
    'no-unneeded-ternary': 'error',
    'no-whitespace-before-property': PRETTIER,
    'nonblock-statement-body-position': PRETTIER,
    'object-curly-newline': PRETTIER,
    'object-property-newline': PRETTIER,
    'object-curly-spacing': PRETTIER,
    'one-var': 'off',
    'one-var-declaration-per-line': PRETTIER,
    'operator-assignment': 'error',
    'operator-linebreak': PRETTIER,
    'padded-blocks': PRETTIER,
    'padding-line-between-statements': [
      'error',
      // force a newline after "use-strict"
      { blankLine: 'always', prev: 'directive', next: '*' },
      // force a newline after the last require statement
      { blankLine: 'always', prev: 'cjs-import', next: '*' },
      { blankLine: 'any', prev: 'cjs-import', next: 'cjs-import' },
    ],
    'prefer-object-spread': 'error',
    'quote-props': PRETTIER,
    'quotes': ['error', 'single', { avoidEscape: true }],
    'semi': PRETTIER,
    'semi-spacing': PRETTIER,
    'semi-style': PRETTIER,
    'sort-keys': 'off', // too opinionated
    'sort-vars': 'off',
    'space-before-blocks': PRETTIER,
    'space-before-function-paren': PRETTIER,
    'space-in-parens': PRETTIER,
    'space-infix-ops': PRETTIER,
    'space-unary-ops': PRETTIER,
    'spaced-comment': ['error', 'always'],
    'switch-colon-spacing': PRETTIER,
    'template-tag-spacing': PRETTIER,
    'unicode-bom': PRETTIER,
    'wrap-regex': PRETTIER,

    // ES6
    'arrow-body-style': PRETTIER,
    'arrow-parens': PRETTIER,
    'arrow-spacing': PRETTIER,
    'constructor-super': 'error',
    'generator-star-spacing': PRETTIER,
    'no-class-assign': 'error',
    'no-confusing-arrow': ['error', { allowParens: false }],
    'no-const-assign': 'error',
    'no-dupe-class-members': 'error',
    'no-duplicate-imports': ['error', { includeExports: true }],
    'no-new-symbol': 'error',
    'no-restricted-imports': 'off',
    'no-this-before-super': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'no-var': 'off',
    'object-shorthand': ['error', 'properties'],
    'prefer-arrow-callback': 'off',
    'prefer-const': ['error', { destructuring: 'all' }],
    'prefer-destructuring': 'off', // too opinionated
    'prefer-numeric-literals': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'off',
    'require-yield': 'error',
    'rest-spread-spacing': PRETTIER,
    'sort-imports': 'off', // imports not used
    'symbol-description': 'error',
    'template-curly-spacing': PRETTIER,
    'yield-star-spacing': PRETTIER,
  },
};
