var pizza = {
  disallowKeywords: ['with'],
  disallowKeywordsOnNewLine: ['else'],
  disallowMixedSpacesAndTabs: true,
  disallowMultipleVarDecl: true,
  disallowNewlineBeforeBlockStatements: true,
  disallowQuotedKeysInObjects: true,
  disallowSpaceAfterObjectKeys: true,
  disallowSpaceAfterPrefixUnaryOperators: true,
  disallowSpacesInFunction: {
    beforeOpeningRoundBrace: true,
  },
  disallowSpacesInsideParentheses: true,
  disallowTrailingWhitespace: true,
  maximumLineLength: {
    value: 80,
    allExcept: ['urlComments', 'require', 'regex']
  },
  requireCapitalizedConstructors: true,
  requireCurlyBraces: [
    'if',
    'else',
    'for',
    'while',
    'do',
    'try',
    'catch',
  ],
  requireSpaceAfterKeywords: [
    'if',
    'else',
    'for',
    'while',
    'do',
    'switch',
    'case',
    'return',
    'try',
    'catch',
    'typeof',
  ],
  requireSpaceAfterLineComment: true,
  requireSpaceAfterBinaryOperators: true,
  requireSpaceBeforeBinaryOperators: true,
  requireSpaceBeforeBlockStatements: true,
  requireSpaceBeforeObjectValues: true,
  requireSpacesInFunction: {
    beforeOpeningCurlyBrace: true,
  },
  validateIndentation: 2,
  validateLineBreaks: 'LF',
  validateQuoteMarks: {
    mark: "'",
    escape: true,
  },
};

var jshint = {
  bitwise: true,
  eqeqeq: true,
  eqnull: true,
  freeze: true,
  funcscope: true,
  latedef: true,
  mocha: true,
  noarg: true,
  node: true,
  regexp: true,
  strict: true,
  undef: true,
  unused: true,
};